
# Catppuccin Mocha
$background = rgba(1e1e2eFF)
$time_color = rgba(a6e3a1e6)
$date_color = rgba(cdd6f5cc)
$user_color = rgba(585b70d9)
$input_outer = rgba(cba6f7cc)
$input_inner = rgba(31324499)
$input_font = rgba(cdd6f4e6)
$placeholder_fg = cdd6f4
$check_color = rgba(a6e3a1cc)
$fail_color = rgba(f38ba8cc)
