
# Catppuccin Frappe
$background = rgba(303446FF)
$time_color = rgba(a6d189e6)
$date_color = rgba(c6d0f5cc)
$user_color = rgba(626880d9)
$input_outer = rgba(ca9ee6cc)
$input_inner = rgba(41455999)
$input_font = rgba(c6d0f5e6)
$placeholder_fg = c6d0f5
$check_color = rgba(a6d189cc)
$fail_color = rgba(e78284cc)
