
# Gruvbox Dark Soft
$background = rgba(32302fFF)
$time_color = rgba(689d6ae6)
$date_color = rgba(ebdbb2cc)
$user_color = rgba(928374d9)
$input_outer = rgba(b16286cc)
$input_inner = rgba(28282899)
$input_font = rgba(ebdbb2e6)
$placeholder_fg = ebdbb2
$check_color = rgba(98971acc)
$fail_color = rgba(cc241dcc)
