$background = rgba(f2e5bcFF)
$time_color = rgba(689d6ae6)
$date_color = rgba(3c3836cc)
$user_color = rgba(928374d9)
$input_outer = rgba(b16286cc)
$input_inner = rgba(fbf1c799)
$input_font = rgba(3c3836e6)
$placeholder_fg = 3c3836
$check_color = rgba(98971acc)
$fail_color = rgba(cc241dcc)
