# Catppuccin Mocha
set -g pane-active-border-style 'fg=#cba6f7,bg=default' # Mauve border
set -g pane-border-style 'fg=#585b70,bg=default'        # Surface0 border

# Floax Colors
set -g @floax-border-color '#cba6f7'
set -g @floax-text-color '#cdd6f4'

# Minimalist Status Bar
set -g status-style 'bg=#1e1e2e,fg=#cdd6f4'
set -g status-left '#[bg=#a6adc8,fg=#1e1e2e,bold] #S #[bg=#1e1e2e,fg=#a6adc8,nobold] '
set -g status-right '#[fg=#a6adc8,bg=#1e1e2e] %H:%M '
setw -g window-status-current-style 'bg=#cba6f7,fg=#1e1e2e,bold'
setw -g window-status-current-format ' #I:#W '
setw -g window-status-style 'bg=#1e1e2e,fg=#a6adc8'
setw -g window-status-format ' #I:#W '
