
# Core Colors
$background = rgb(f2e5bc)
$foreground = rgb(3c3836)
$cursor = rgb(3c3836)

# Standard Colors (0-7)
$color0 = rgb(fbf1c7)
$color1 = rgb(cc241d)
$color2 = rgb(98971a)
$color3 = rgb(d79921)
$color4 = rgb(458588)
$color5 = rgb(b16286)
$color6 = rgb(689d6a)
$color7 = rgb(7c6f64)

# Bright Colors (8-15)
$color8 = rgb(928374)
$color9 = rgb(9d0006)
$color10 = rgb(79740e)
$color11 = rgb(b57614)
$color12 = rgb(076678)
$color13 = rgb(8f3f71)
$color14 = rgb(427b58)
$color15 = rgb(3c3836)
