# Wallust-generated Hyprlock Config

source = ~/.config/hypr/themes/hyprlock/gruvbox-light.conf 

# BACKGROUND
background {
    monitor =
    path = /home/ugzher/Pictures/Wallpapers/lock.jpeg   
    color = $background
    blur_passes = 1
    contrast = 0.8916
    brightness = 0.7
    vibrancy = 0.2
    vibrancy_darkness = 0.1
}

# GENERAL
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

# Time 
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I:%M")</span>"
    color = $time_color
    font_size = 160
    font_family = Lilex Nerd Font
    position = 0, 370
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = $date_color
    font_size = 28
    font_family = Lilex Nerd Font Bold
    position = 0, 490
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = $USER
    color = $user_color
    font_size = 18
    font_family = Lilex Nerd Font Bold
    position = 0, -180
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $input_outer
    inner_color = $input_inner
    font_color = $input_font
    fade_on_empty = false
    font_family = Lilex Nerd Font
    placeholder_text = <i><span foreground="#$placeholder_fg">🔒 Enter Password</span></i>
    hide_input = false
    check_color = $check_color
    fail_color = $fail_color
    position = 0, -250
    halign = center
    valign = center
}
