# Nord Polar Night Starship Configuration
format = """\
[](fg:#1F1D2E)\
$username\
[](fg:#1F1D2E bg:#26233A)\
$directory\
[](fg:#26233A bg:#403D52)\
$git_branch\
$git_status\
[](fg:#403D52 bg:#1F1D2E )\
$all\
$cmd_duration\
$jobs\
$time\
$character"""

add_newline = true

[line_break]
disabled = true

[username]
show_always = true
style_user = "fg:#9ccfd8 bg:#1f1d2e"
style_root = "fg:#1f1d2e bg:#1f1d2e"
format = '[ ]($style)'

[directory]
style = "fg:#c4a7e7 bg:#26233a"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~" = " ~"
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[git_branch]
symbol = ""
style = "fg:#31748f bg:#403d52"
format = '[ $symbol $branch(:$remote_branch) ]($style)'

[git_status]
style = "fg:#9ccfd8 bg:#403d52"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"
format = '[$all_status$ahead_behind ]($style)'

[aws]
symbol = " "
style = "fg:#eb6f92 bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[c]
symbol = ""
style = "fg:#9ccfd8 bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[docker_context]
symbol = ""
style = "fg:#9ccfd8 bg:#1f1d2e"
format = '[ $symbol $context]($style) $path '

[elixir]
symbol = ""
style = "fg:#c4a7e7 bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[golang]
symbol = ""
style = "fg:#9ccfd8 bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[haskell]
symbol = "λ"
style = "fg:#c4a7e7 bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[java]
symbol = ""
style = "fg:#f6c177 bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[lua]
symbol = ""
style = "fg:#9ccfd8 bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[nodejs]
symbol = ""
style = "fg:#31748f bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[python]
symbol = ""
style = "fg:#f6c177 bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[rust]
symbol = ""
style = "fg:#eb6f92 bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[bun]
symbol = ""
style = "fg:#f6c177 bg:#1f1d2e"
format = '[ $symbol ($version )]($style)'

[cmd_duration]
min_time = 1
style = "fg:#f6c177 bg:#1f1d2e"
format = "[ $duration]($style)"

[jobs]
symbol = "華"
style = "fg:#EBCB8B bg:#3B4252"
format = "[ $symbol]($style)"

[time]
disabled = true
time_format = "%R"
style = "fg:#f6c177 bg:#1f1d2e"
format = '[](fg:#1f1d2e $style)[  $time ](fg:#9ccfd8 $style)'

[character]
success_symbol = "[ ](fg:#1f1d2e)"
error_symbol = "[ ](fg:#eb6f92)"
