# Wallust Generated Starship Configuration

# Fixed the formatting blocks so the arrows perfectly blend into the next background color
format = """\
[](fg:#A17493)\
$username\
[](fg:#A17493 bg:#918074)\
$directory\
[](fg:#918074 bg:#66857C)\
$git_branch\
$git_status\
[](fg:#66857C bg:#03040A)\
$all\
$cmd_duration\
$jobs\
$time\
$character"""

add_newline = true

[line_break]
disabled = true

[username]
show_always = true
style_user = "fg:#020308 bg:#A17493"
style_root = "fg:#020308 bg:#222431"
format = '[ ]($style)'

[directory]
style = "fg:#020308 bg:#918074"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~" = " ~"
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[git_branch]
symbol = ""
style = "fg:#020308 bg:#66857C"
format = '[ $symbol $branch(:$remote_branch) ]($style)'

[git_status]
style = "fg:#020308 bg:#66857C"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"
format = '[$all_status$ahead_behind ]($style)'

[aws]
symbol = " "
style = "fg:#222431 bg:#03040A"
format = '[ $symbol ($version )]($style)'

[c]
symbol = ""
style = "fg:#A17493 bg:#03040A"
format = '[ $symbol ($version )]($style)'

[docker_context]
symbol = ""
style = "fg:#A17493 bg:#03040A"
format = '[ $symbol $context]($style) $path '

[elixir]
symbol = ""
style = "fg:#918074 bg:#03040A"
format = '[ $symbol ($version )]($style)'

[golang]
symbol = ""
style = "fg:#A17493 bg:#03040A"
format = '[ $symbol ($version )]($style)'

[haskell]
symbol = "λ"
style = "fg:#918074 bg:#03040A"
format = '[ $symbol ($version )]($style)'

[java]
symbol = ""
style = "fg:#778093 bg:#03040A"
format = '[ $symbol ($version )]($style)'

[lua]
symbol = ""
style = "fg:#A17493 bg:#03040A"
format = '[ $symbol ($version )]($style)'

[nodejs]
symbol = ""
style = "fg:#66857C bg:#03040A"
format = '[ $symbol ($version )]($style)'

[python]
symbol = ""
style = "fg:#778093 bg:#03040A"
format = '[ $symbol ($version )]($style)'

[rust]
symbol = ""
style = "fg:#222431 bg:#03040A"
format = '[ $symbol ($version )]($style)'

[bun]
symbol = ""
style = "fg:#778093 bg:#03040A"
format = '[ $symbol ($version )]($style)'

[cmd_duration]
min_time = 1
style = "fg:#778093 bg:#03040A"
format = "[ $duration]($style)"

[jobs]
symbol = "華"
style = "fg:#778093 bg:#03040A"
format = "[ $symbol]($style)"

[time]
disabled = true
time_format = "%R"
style = "fg:#778093 bg:#03040A"
format = '[](fg:#03040A $style)[  $time ](fg:#A17493 $style)'

[character]
success_symbol = "[ ](fg:#4B5162)"
error_symbol = "[ ](fg:#222431)"
